### ISSUE TITLE
http://fsprojects.github.io/FsBlog design is broken

### ISSUE THREAD

**Issue by forki** [fsprojects/FsBlog#32]

**Comment by kunjee17** [comment]
It is still broken. I guess it can't reach the site where CSS is hosted.

**Comment by jasonsturges** [comment]
Timeouts for saxonmatt.co.uk are 1.3 minutes, totaling 2.5 minutes for resources to error before rendering the page.  Clearly should have been relative to gh-pages.

![network](https://cloud.githubusercontent.com/assets/1213591/11078629/c4b3273e-87cc-11e5-82d7-dfaedb97df21.png)

**Comment by forki** [comment]
Care to send a pull request?

**Comment by jasonsturges** [comment]
Looks like you just beat me to it.

**Comment by forki** [comment]
Sorry I needed to see what's wrong. There are still lots of issues with it

**Comment by jasonsturges** [comment]
@forki No worries, just reject my pull request.
