### ISSUE TITLE
Generated links for "preview" should be relative

### ISSUE THREAD

**Issue by WallaceKelly** [fsprojects/FsBlog#51]
If I do 'fake preview`, it "generates the site and then starts up a local web server." That's really convenient, except...

All the links are *absolute* to the production site.

The consequence is that I cannot navigate to my newly added content or edits, because clicking on any link takes me to the production site. It seems like it should be navigating around localhost:8080.

For previews, the links to should be relative.

![whynotrelative](https://cloud.githubusercontent.com/assets/698424/11966465/f5a812dc-a8c9-11e5-829f-6c097484f6f1.png)

**Comment by cdrnet** [comment]
This is fixed in ca5c1b6 where in (and only in) preview mode the root URL is fixed to point to the local suave http server instead of what is in the config.
