### ISSUE TITLE
Advertise RSS feed in <link rel="alternate">

### ISSUE THREAD

**Issue by svick** [fsprojects/FsBlog#53]
I think the RSS feed of the blog should be advertised in the HTML head of each page of the blog by using `<link rel="alternate"  type="application/rss+xml">`. Without this, the feed is very hard to find.

I personally use Bookmarks → Subscribe to this page in Firefox to find the RSS feed, which uses URL from the `<link>`.

**Comment by cdrnet** [comment]
Implemented in all themes, thanks for opening the issue!
