### ISSUE TITLE
Wrong argument order for mono FAKE exe?

### ISSUE THREAD

**Issue by theimowski** [fsprojects/FsBlog#55]
Currently the  script name `fsblog.fsx` comes as last argument:
```mono --runtime=v4.0 packages/FAKE/tools/FAKE.exe $@ --fsiargs -d:MONO fsblog.fsx```
however usage for FAKE specifies that scipt path comes first:
```
tomasz@theimowski-ubuntu:~/github/FsBlog$ mono packages/FAKE/tools/FAKE.exe --help
-------------------
 FAKE usage
-------------------

    fake.exe [<scriptPath>] [<targetName>] [options]
```

**Comment by cdrnet** [comment]
Yes, it is indeed wrong in the mono case in both `build` and `fake`. Thanks!

**Comment by cdrnet** [comment]
We should fix it, but is it as is actually broken in your case? Turns out I've used the wrong order for years in all my projects without any problems.

**Comment by theimowski** [comment]
Yeah I tried to type 

    ./fake new post="title"

But got error msg indicating there is no "new" target, so I ended up calling FAKE directly with different arg order
