### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/FsBlog#64]
IS there development in the planning? Since I would love to add one F-Sharp entry to https://www.staticgen.com/

**Comment by cdrnet** [comment]
Not from my side, unfortunately.

**Comment by ShalokShalom** [comment]
Thanks a lot.

**Comment by ShalokShalom** [comment]
Seems like this is in use, at least: (current blog post from a few months ago) 
https://github.com/jet/FsBlog

**Comment by dsyme** [comment]
If anyone would like to take this over please shout, otherwise we will move this to the fsprojects archive sooner or later
