### ISSUE TITLE
Add deploy command

### ISSUE THREAD

**Issue by MattDrivenDev** [fsprojects/FsBlog#9]
I'm rather hoping we can very easily run a `fake deploy` command and it will do all the work created to:
- Regenerate the website.
- Ensure that there is a `./deploy` folder which is a local clone of the `FsBlog/gh-pages` branch, hooked up to the remote.
- Copy the output into `./deploy` folder.
- Add changes and commit using a standard commit message.
- Push `./deploy` back to `remote/gh-pages`.

**Comment by ShalokShalom** [comment]
This can be closed.
